version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: itemreminder-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: itemreminder
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - itemreminder-network

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: itemreminder-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - itemreminder-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: itemreminder-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/itemreminder?authSource=admin
      MQTT_BROKER: mqtt://mosquitto:1883
      JWT_SECRET: your-super-secret-jwt-key-change-this
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - mosquitto
    networks:
      - itemreminder-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: itemreminder-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_SOCKET_URL: http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - itemreminder-network

volumes:
  mongodb_data:

networks:
  itemreminder-network:
    driver: bridge
